### ISSUE TITLE
What the program does and What bugs are present: 

### ISSUE THREAD

**Issue by Ahmed-Fawzy14** [Ahmed-Fawzy14/Logic-Circuit-Simulator#2]
Each member will enter what bugs they see in the code and what works.

**Comment by Ahmed-Fawzy14** [comment]
What Works:
- Classes are done 
- Operator Function is working for sample inputs 
- Logic for run function is working

**Comment by Ahmed-Fawzy14** [comment]
Current Bugs:
- Problem with mapping values from usedGates and cir_Input_Names (sometimes skips an index)
- Need to unify how we test so we can it can work for any test circuit

**Comment by AhmedAbdeen7** [comment]
Another problem that needs to be addressed is that the program's code needs to be more modular.

**Comment by Ahmed-Fawzy14** [comment]
Fixed bugs in operator.
